---
all:
  children:

    # OPNsense firewall / internet gateway
    firewall:
      hosts:
        opnsense:
          ansible_host: 10.1.90.1

    # Linux machines managed by Ansible
    linux_targets:
      hosts:
        linux-test:
          ansible_host: 10.1.90.10
